name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # 若你要黑視窗版本，用下面這行：
        pyinstaller --console --onefile Main.py
        dir dist
        # 若你要無視窗版本，用下面這行：
      # pyinstaller --noconsole --onefile Main.py
        
        
        

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/Main.exe

    - name: Create Tag
      id: tag
      shell: pwsh
      run: |
        # 生成 tag
        $TAG_NAME = "v$(Get-Date -Format 'yyyyMMddHHmmss')"
        echo "TAG_NAME=$TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        # 設定 git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # 建立 tag
        git tag $TAG_NAME

        # push tag 用 token 認證
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME


    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: dist/Main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
